//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: api/zksnark.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Protocol_TronZksnarkClient`, then call methods of this protocol to make API calls.
internal protocol Protocol_TronZksnarkClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Protocol_TronZksnarkClientInterceptorFactoryProtocol? { get }

  func checkZksnarkProof(
    _ request: Protocol_ZksnarkRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Protocol_ZksnarkRequest, Protocol_ZksnarkResponse>
}

extension Protocol_TronZksnarkClientProtocol {
  internal var serviceName: String {
    return "protocol.TronZksnark"
  }

  /// Unary call to CheckZksnarkProof
  ///
  /// - Parameters:
  ///   - request: Request to send to CheckZksnarkProof.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func checkZksnarkProof(
    _ request: Protocol_ZksnarkRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Protocol_ZksnarkRequest, Protocol_ZksnarkResponse> {
    return self.makeUnaryCall(
      path: "/protocol.TronZksnark/CheckZksnarkProof",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCheckZksnarkProofInterceptors() ?? []
    )
  }
}

internal protocol Protocol_TronZksnarkClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'checkZksnarkProof'.
  func makeCheckZksnarkProofInterceptors() -> [ClientInterceptor<Protocol_ZksnarkRequest, Protocol_ZksnarkResponse>]
}

internal final class Protocol_TronZksnarkClient: Protocol_TronZksnarkClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Protocol_TronZksnarkClientInterceptorFactoryProtocol?

  /// Creates a client for the protocol.TronZksnark service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Protocol_TronZksnarkClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Protocol_TronZksnarkProvider: CallHandlerProvider {
  var interceptors: Protocol_TronZksnarkServerInterceptorFactoryProtocol? { get }

  func checkZksnarkProof(request: Protocol_ZksnarkRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Protocol_ZksnarkResponse>
}

extension Protocol_TronZksnarkProvider {
  internal var serviceName: Substring { return "protocol.TronZksnark" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "CheckZksnarkProof":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Protocol_ZksnarkRequest>(),
        responseSerializer: ProtobufSerializer<Protocol_ZksnarkResponse>(),
        interceptors: self.interceptors?.makeCheckZksnarkProofInterceptors() ?? [],
        userFunction: self.checkZksnarkProof(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Protocol_TronZksnarkServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'checkZksnarkProof'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCheckZksnarkProofInterceptors() -> [ServerInterceptor<Protocol_ZksnarkRequest, Protocol_ZksnarkResponse>]
}
